name: CI
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.10"
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/checkout@v2
      - run: pip install -e .[test]
      - run: py.test -vvv --cov .
      - uses: codecov/codecov-action@v2
  Lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v3.0.0
